name: Test

on:
  workflow_dispatch:
  push:
    tags:
    - '*'

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-18.04
    outputs: # Output contains the upload url. Will be reused on upload release
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

  linux:
    name: Linux test
    runs-on: ubuntu-18.04
    timeout-minutes: 60
    needs: create-release
    env:
      TAG_NAME: ${{ github.ref_name }}
    steps:
      - name: Download repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Generate artifact
        run: |
          echo "xxx" >> artifact.txt

      - name: Upload release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: artifact.txt
          asset_name: artifact.txt
          asset_content_type: text/plain


