name: Test

on:
  push:
    tags:
    - '*'

jobs:
  linux:
    name: Linux test
    runs-on: ubuntu-18.04
    timeout-minutes: 60
    steps:
      - name: Download repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Echo env vars
        run: python3 test.py --version=1.2.3