name: Test

on:
  workflow_dispatch:
  push:
    tags:
    - '*'

jobs:
  linux:
    name: Linux test
    runs-on: ubuntu-18.04
    timeout-minutes: 60
    env:
      TAG_NAME: ${{ github.ref_name }}
    steps:
      - name: Download repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Echo env vars
        run: |
          python3 test.py --version=${{ github.ref_name }}
          python3 test.py --version=$TAG_NAME
